---
permalink: installconfig/configuring-hardware.html 
sidebar: sidebar 
keywords: storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking 
summary: 为设备通电后、您可以配置StorageGRID 要使用的网络连接。  
---
= 设置 StorageGRID 设备硬件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
为设备通电后、您可以配置StorageGRID 要使用的网络连接。



== 所需硬件配置



=== 网络连接

您必须配置并验证所有设备所需的网络连接：

* link:../installconfig/accessing-storagegrid-appliance-installer.html["访问设备安装程序"]
* link:../installconfig/configuring-network-links.html["配置网络链路"]
* link:../installconfig/verifying-port-level-network-connections.html["验证端口级别的网络连接"]




=== BMC 接口

如果要安装以下设备之一，则必须 link:../installconfig/configuring-bmc-interface.html["配置基板管理控制器（BMC）接口"]：

* SG100
* SG110
* SG120
* SG1000
* SG1100
* SG1200
* SGF6024
* GF6112
* SGF6212
* SG6060
* SG6160
* SG6260


您可以使用 BMC 界面为设备配置 SNMP 和其他低级设置。它还可以对硬件安装进行故障排除，确定设备的电源状态，并控制设备上的识别指示灯。

要了解有关 BMC 可以使用哪些功能的更多信息，请参阅 link:../commonhardware/use-bmc.html["使用BMC界面"]。



== 可选硬件配置



=== SANtricity 系统管理器

如果您拥有以下设备之一，则可以 link:../installconfig/accessing-and-configuring-santricity-system-manager.html["配置 SANtricity System Manager"]：

* SG5712
* SG5760
* SG5812
* SG5860
* SGF6024
* SG6060
* SG6160
* SG6260


SANtricity System Manager 软件允许您：

* 监控设备的系统性能数据、硬件组件状态和支持功能
* 管理驱动器安全密钥、SNMP 和 syslog 警报以及用于访问 SANtricity System Manager 的管理员密码
* 配置对 E 系列 AutoSupport 的访问




=== 启用节点或驱动器加密

您可以link:../installconfig/optional-enabling-node-encryption.html["启用节点或驱动器加密"]保护设备中的驱动器和磁盘。



=== 更改 RAID 模式

您可以link:../installconfig/optional-changing-raid-mode.html["更改存储设备的 RAID 模式"]以满足您的存储和恢复需求。

以下设备支持更改 RAID 模式：

* SG5760
* SG5860
* SGF6024
* SG6060
* SG6160
* SG6260




=== 重新映射网络端口

您可以link:../installconfig/optional-remapping-network-ports-for-appliance.html["重新映射设备上的网络端口"]优化网络连接。
