---
permalink: installconfig/deploying-appliance-storage-node.html 
sidebar: sidebar 
keywords: storage node, storage appliance, deploy node, deploying node, node, deploy, deploying 
summary: 安装和配置存储设备后，您可以将其部署为 StorageGRID 系统中的存储节点。将设备部署为存储节点时，您可以使用设备上随附的 StorageGRID 设备安装程序。 
---
= 部署设备存储节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安装和配置存储设备后，您可以将其部署为 StorageGRID 系统中的存储节点。将设备部署为存储节点时，您可以使用设备上随附的 StorageGRID 设备安装程序。

.开始之前
* 如果要克隆设备节点、请继续执行以下操作 link:../commonhardware/appliance-node-cloning-procedure.html["设备节点克隆"] 流程。
* 此设备已安装在机架或机柜中，并已连接到您的网络并已启动。
* 已使用 StorageGRID 设备安装程序为此设备配置网络链路， IP 地址和端口重新映射（如果需要）。
* 您知道分配给设备计算控制器的一个 IP 地址。您可以对任何已连接的 StorageGRID 网络使用此 IP 地址。
* 已部署 StorageGRID 系统的主管理节点。
* StorageGRID 设备安装程序的 IP 配置页面上列出的所有网格网络子网均已在主管理节点上的网格网络子网列表中定义。
* 您的服务笔记本电脑具有受支持的 Web 浏览器。


.关于此任务
每个存储设备都用作一个存储节点。任何设备都可以连接到网格网络，管理网络和客户端网络

要在 StorageGRID 系统中部署设备存储节点，请访问 StorageGRID 设备安装程序并执行以下步骤：

* 您可以指定或确认主管理节点的 IP 地址以及存储节点的名称。
* 您可以开始部署，并等待卷配置完毕并安装软件。
* 当安装暂停完成设备安装任务后，您可以通过登录到网格管理器，批准所有网格节点并完成 StorageGRID 安装和部署过程来恢复安装。



NOTE: 如果需要一次部署多个设备节点、可以使用以下链接自动执行安装过程：../installconfig/Automate-Appliance安装和配置.html#Automate-with配置sga-py-script[`configure-sga.py` 设备安装脚本]。

* 如果要执行扩展或恢复操作，请按照相应说明进行操作：
+
** 要将设备存储节点添加到现有StorageGRID系统，请参见的说明 https://docs.netapp.com/us-en/storagegrid/expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html["正在添加网格节点"^]。
** 要在恢复操作中部署设备存储节点，请参见说明 https://docs.netapp.com/us-en/storagegrid/maintain/recovering-storagegrid-appliance-storage-node.html["恢复设备存储节点"^]。




.步骤
. 打开浏览器，然后输入设备计算控制器的 IP 地址之一。+
`*https://_Controller_IP_:8443*`
+
此时将显示 StorageGRID 设备安装程序主页页面。

. 选择*节点类型*。有关详细信息，请参见 https://docs.netapp.com/us-en/storagegrid/primer/what-storage-node-is.html#types-of-storage-nodes["存储节点的类型"]。
+

NOTE: 只能在设备部署期间选择仅元数据。如果选择"仅元数据"作为存储节点类型、则在部署设备后将无法更改此类型。

. 在*Node name*字段中，提供要用于此设备节点的系统名称，然后单击*Save*。
+
此处显示的名称将是设备节点的系统名称。内部StorageGRID 操作需要系统名称、并且无法更改。

. 在 * 主管理节点连接 * 部分中，确定是否需要指定主管理节点的 IP 地址。
+
如果先前已在此数据中心中安装了其他节点，则 StorageGRID 设备安装程序可以自动发现此 IP 地址，前提是主管理节点或至少一个配置了 admin_IP 的其他网格节点位于同一子网上。

. 如果未显示此 IP 地址或您需要更改此 IP 地址，请指定地址：
+
[cols="1a,2a"]
|===
| 选项 | Description 


 a| 
手动输入 IP
 a| 
.. 清除*启用管理节点发现*复选框。
.. 手动输入 IP 地址。
.. 单击 * 保存 * 。
.. 等待连接状态，使新 IP 地址准备就绪。




 a| 
自动发现所有已连接的主管理节点
 a| 
.. 选中*启用管理节点发现*复选框。
.. 等待显示发现的 IP 地址列表。
.. 为要部署此设备存储节点的网格选择主管理节点。
.. 单击 * 保存 * 。
.. 等待连接状态，使新 IP 地址准备就绪。


|===
. 在*安装*部分中、确认当前状态为"准备开始安装" `_node name_` 使用主管理节点进入网格 `_admin_ip_` "并启用了*开始安装*按钮。
+
如果未启用 * 开始安装 * 按钮，则可能需要更改网络配置或端口设置。有关说明、请参见设备的维护说明。

+

NOTE: 如果要将存储节点设备部署为节点克隆目标、请在此停止部署过程并继续
link:../commonhardware/appliance-node-cloning-procedure.html["节点克隆操作步骤"]。

. 在 StorageGRID 设备安装程序主页中，单击 * 开始安装 * 。
+
当前状态更改为"`正在安装、`"和 link:../installconfig/monitoring-appliance-installation.html["监控器安装页面"] 将显示

+

NOTE: 如果需要手动访问监控器安装页面，请单击 * 监控安装 * 。

. 如果网格包含多个设备存储节点，请对每个设备重复这些步骤。
+

NOTE: 如果您需要一次部署多个设备存储节点、可以使用以下链接自动执行安装过程：../installconfig/Automate-Appliance安装和配置.html#Automate-with配置sga-py-script[`configure-sga.py` 设备安装脚本]。


