---
permalink: sg5800/replace-controller-5800sg.html 
sidebar: sidebar 
keywords:  
summary:  
---
= 更换StorageGRID SG5800 控制器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果SG可能性 能达到最佳状态或发生故障、您可能需要更换SGsfing控制器。

.开始之前
* 您的更换控制器的部件号与要更换的控制器相同。
* 您可以通过标签来识别连接到控制器的每个缆线。


.关于此任务
更换控制器后，您将无法访问设备存储节点。如果 SG5800 控制器功能正常，您可以在此过程开始时执行受控关机。


NOTE: 如果在安装 StorageGRID 软件之前更换控制器，则在完成此操作步骤 后，您可能无法立即访问 StorageGRID 设备安装程序。虽然您可以从与设备位于同一子网上的其他主机访问StorageGRID设备安装程序、但不能从其他子网上的主机访问该安装程序。此情况应在 15 分钟内自行解决（当原始控制器的任何 ARP 缓存条目超时），或者您也可以通过手动从本地路由器或网关清除任何旧的 ARP 缓存条目来立即清除此情况。

.步骤
. 关闭SG完全 控制器。
+
.. 登录到网格节点：
+
... 输入以下命令： `ssh admin@grid_node_IP`
... 输入中列出的密码 `Passwords.txt` 文件
... 输入以下命令切换到root： `su -`
... 输入中列出的密码 `Passwords.txt` 文件
+
以root用户身份登录后、提示符将从变为 `$` to `#`。





. 关闭SG完全 控制器：
+
*`shutdown -h now`*

. 如果连接到控制器的 StorageGRID 网络使用 DHCP 服务器：
+
.. 记下替代控制器上端口的 MAC 地址（位于控制器上的标签上）。
.. 请网络管理员更新原始控制器的 IP 地址设置，以反映替代控制器的 MAC 地址。
+

NOTE: 在将替换控制器插入设备之前，必须确保原始控制器的 IP 地址已更新。否则，控制器启动时将获取新的 DHCP IP 地址，并且可能无法重新连接到StorageGRID。此步骤适用于连接到控制器的所有StorageGRID网络。



. 从设备中删除控制器：
+
.. 戴上 ESD 腕带或采取其他防静电预防措施。
.. 为缆线贴上标签，然后断开缆线和 SFP 的连接。
+

NOTE: 为防止性能下降、请勿扭曲、折叠、挤压或踩踏缆线。
通过挤压凸轮把手上的闩锁，直到其释放，然后打开右侧的凸轮把手，将控制器从设备中释放。

.. 用两只手和凸轮把手将控制器滑出设备。
+

NOTE: 请始终用双手支撑控制器的重量。



. 将替代控制器安装到设备中。
+
.. 将控制器翻转，使可拆卸盖朝下。
.. 在凸轮把手处于打开位置的情况下，将控制器完全滑入设备中。
.. 将凸轮把手移至左侧，将控制器锁定到位。
.. 更换缆线。


. 控制器重新启动且设备重新加入电网后，确认设备存储节点出现在电网管理器中并且没有出现警报。


更换部件后，按照套件随附的 RMA 说明将故障部件退回 NetApp 。请参见 https://mysupport.netapp.com/site/info/rma["部件退回和放大器；更换"] 第页，了解更多信息。
