---
permalink: sg5800/replace-drives-12-24.html 
sidebar: sidebar 
keywords: E4000 replace drive, replacing E4000 drive, E4000 replace drive, replacing E4000 drive, E4000, E-Series, eseries. sg5812 
summary: 您可以更换SG5812中的驱动器。 
---
= 更换SG5812中的驱动器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更换SG5812中的驱动器。

.关于此任务
StorageGRID网格管理器可监控设备状态、并在发生驱动器故障时发出警报。  当网格管理器发出警报时、您可以随时使用SANtricity系统管理器中的恢复专家来获取有关发生故障的特定驱动器的详细信息。  驱动器发生故障时，其琥珀色警示 LED 亮起。您可以在存储阵列接收 I/O 时热插拔故障驱动器

.开始之前
* 查看驱动器处理要求
* 确保您已具备以下条件：
+
** NetApp 为您的控制器架或驱动器架支持的替代驱动器。
** ESD 腕带，或者您已采取其他防静电预防措施。
** 访问SANtricity系统管理器：
+
*** 在网格管理器中，选择*NODE*>*_Appliance NODE_*> SANtricity System Manager*。控制器信息位于上 https://docs.netapp.com/us-en/storagegrid-118/monitor/viewing-santricity-system-manager-tab.html["SANtricity系统管理器选项卡"]。
*** 将Management Station中的浏览器指向控制器的域名或IP地址。








== 第 1 步：准备更换驱动器

检查 SANtricity System Manager 中的恢复 Guru 并完成所有前提步骤，以便准备更换驱动器。然后，您可以找到故障组件。

.步骤
. 如果 SANtricity System Manager 中的恢复 Guru 已通知您驱动器出现 _ 即将发生故障 _ ，但驱动器尚未出现故障，请按照恢复 Guru 中的说明对驱动器进行故障转移。
. 如果需要，请使用 SANtricity 系统管理器确认您有合适的替代驱动器。
+
.. 选择 * 硬件 * 。
.. 在磁盘架图中选择故障驱动器。
.. 单击驱动器以显示其上下文菜单，然后选择 * 查看设置 * 。
.. 确认替代驱动器的容量等于或大于要更换的驱动器，并且具有您期望的功能。
+
例如，不要尝试将硬盘驱动器（ HDD ）更换为固态磁盘（ SSD ）。同样，如果要更换支持安全保护的驱动器，请确保更换的驱动器也支持安全保护。



. 如果需要，请使用 SANtricity 系统管理器查找存储阵列中的驱动器。从 "Hardware" 页面上的驱动器上下文菜单中，选择 * 打开定位灯 * 。
+
驱动器的警示 LED （琥珀色）将闪烁，以便您确定要更换的驱动器。

+

NOTE: 如果要更换具有挡板的磁盘架中的驱动器，则必须卸下挡板才能看到驱动器 LED 。





== 第 2 步：删除故障驱动器

删除故障驱动器以更换为新驱动器。

.步骤
. 拆开备用驱动器的包装，并将其放在磁盘架附近的无静电平面上。
+
节省所有包装材料。

. 按下故障驱动器上的释放按钮。
. 打开凸轮把手，然后轻轻滑出驱动器。
. Wait 30 seconds.
. 用双手将驱动器从磁盘架中取出。
. Place the drive on an antistatic, cushioned surface away from magnetic fields.
. 等待 30 秒，使软件识别出驱动器已被删除。
+

NOTE: 如果您意外删除了活动驱动器，请至少等待 30 秒，然后重新安装它。有关恢复操作步骤，请参阅存储管理软件。





== 第 3 步：安装新驱动器

安装新驱动器以更换故障驱动器。


CAUTION: 删除故障驱动器后，请尽快安装替代驱动器。否则，设备可能会过热。

.步骤
. 打开凸轮把手。
. 用两只手将替代驱动器插入打开的托架中，用力推动，直到驱动器停止为止。
. 慢慢合上凸轮把手，直到驱动器完全固定在中板中，并且把手卡入到位。
+
正确插入驱动器后，驱动器上的绿色 LED 将亮起。

+

NOTE: 根据您的配置，控制器可能会自动将数据重建到新驱动器。如果磁盘架使用热备用驱动器，则控制器可能需要对热备用磁盘执行完整重建，然后才能将数据复制到更换的驱动器。此重建过程会增加完成此操作步骤所需的时间。





== 第 4 步：完成驱动器更换

完成驱动器更换，以确认新驱动器运行正常。

.步骤
. 检查您更换的驱动器上的电源 LED 和警示 LED 。（首次插入驱动器时，其警示 LED 可能会亮起。但是， LED 应在一分钟内熄灭。）
+
** 电源 LED 亮起或闪烁，警示 LED 熄灭：表示新驱动器正常工作。
** 电源 LED 熄灭：表示驱动器可能安装不正确。Remove the drive, wait 30 seconds, and then reinstall it.
** 警示 LED 亮起：表示新驱动器可能出现故障。Replace it with another new drive.


. 如果 SANtricity 系统管理器中的恢复 Guru 仍显示问题描述，请选择 * 重新检查 * 以确保问题已解决。
. 如果 Recovery Guru 指示驱动器重建未自动启动，请手动启动重建，如下所示：
+

NOTE: 只有在技术支持或 Recovery Guru 指示执行此操作时，才能执行此操作。

+
.. 选择 * 硬件 * 。
.. 单击已更换的驱动器。
.. 从驱动器的上下文菜单中，选择 * 重建 * 。
.. 确认要执行此操作。
+
驱动器重建完成后，卷组将处于最佳状态。



. 根据需要重新安装挡板。
. 按照套件随附的 RMA 说明将故障部件退回 NetApp 。


.下一步是什么？
驱动器更换已完成。您可以恢复正常操作。
