---
permalink: commonhardware/considerations-and-requirements-for-appliance-node-cloning.html 
sidebar: sidebar 
keywords: storagegrid, clone appliance node, cloning appliance node 
summary: 在克隆设备节点之前，您必须了解注意事项和要求。 
---
= 设备节点克隆的注意事项和要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在克隆设备节点之前，您必须了解注意事项和要求。



== 更换设备的硬件要求

确保替代设备符合以下标准：

* 源节点（要更换的设备）和目标（新）设备必须为相同类型的设备：
+
** 您只能将管理节点设备或网关节点设备克隆到新的服务设备。
** 您只能将存储节点设备克隆到新的存储设备。


* 对于管理节点或网关节点设备、源节点设备和目标设备不必是相同类型的设备；但是、更改设备类型可能需要更换缆线或SFP模块。
+
例如，您可以将 SG1000 节点设备更换为 SG100 ，也可以将 SG100 设备更换为 SG1000 设备。

* 对于存储节点设备、源节点设备和目标设备不必是相同类型的设备；但是、目标设备必须比源设备具有更大的存储容量。
+
例如、您可以将SG5700节点设备更换为SG6000设备。



请联系您的 StorageGRID 销售代表，以帮助您选择兼容的替代设备来克隆 StorageGRID 安装中的特定设备节点。



== 准备克隆设备节点

克隆设备节点之前，您必须具有以下信息：

* 从网络管理员处获取网格网络的临时 IP 地址，以便在初始安装期间与目标设备配合使用。如果源节点属于管理网络或客户端网络，请获取这些网络的临时 IP 地址。
+
临时IP地址通常与要克隆的源节点设备位于同一子网上、克隆完成后不需要。源设备和目标设备都必须连接到 StorageGRID 的主管理节点，才能建立克隆连接。

* 确定要使用哪个网络克隆数据传输流量，从而在不降低 StorageGRID 网络性能或数据可用性的情况下提供最佳数据传输性能。
+

NOTE: 使用 1-GbE 管理网络进行克隆数据传输会导致克隆速度变慢。

* 确定目标设备是否将使用密钥管理服务器（ KMS ）进行节点加密，以便在克隆之前在初始目标设备安装期间启用节点加密。您可以检查源设备节点上是否已启用节点加密、如中所述 link:../installconfig/optional-enabling-node-encryption.html["正在启用节点加密"]。
+
源节点和目标设备可以具有不同的节点加密设置。在数据传输期间以及目标节点重新启动并加入网格时，系统会自动执行数据解密和加密。

* 确定是否应更改目标设备上的 RAID 模式及其默认设置，以便您可以在克隆之前的初始目标设备安装期间指定此信息。您可以在网格管理器的 * 节点 * 页面上查看有关源设备节点当前 RAID 模式的信息。选择设备的 * 存储 * 选项卡。
+
源节点和目标设备可以具有不同的 RAID 设置。

* 规划足够的时间以完成节点克隆过程。将数据从运行中的存储节点传输到目标设备可能需要几天时间。计划一次克隆，尽可能地减少对业务的影响。
* 一次只能克隆一个设备节点。克隆可能会阻止您同时执行其他 StorageGRID 维护功能。
* 克隆设备节点后，您可以使用已恢复预安装状态的源设备作为克隆另一个兼容节点设备的目标。

