---
permalink: commonhardware/considerations-and-requirements-for-appliance-node-cloning.html 
sidebar: sidebar 
keywords: storagegrid, clone appliance node, cloning appliance node 
summary: 在克隆设备节点之前，您必须了解注意事项和要求。 
---
= StorageGRID 设备节点克隆的要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在克隆设备节点之前，您必须了解注意事项和要求。


TIP: 网关节点的节点克隆功能已禁用。要替换网关节点，请先将其退役，然后执行扩展以添加新的设备网关节点。网关节点的退役和扩展过程比存储节点快得多。



[[hardware-requirements-for-the-replacement-appliance]]
== 更换设备的硬件要求

确保替代设备符合以下标准：

* 源节点（要更换的设备）和目标（新）设备必须为相同类型的设备：
+
** 您只能将管理节点设备克隆到新的服务设备。
** 您只能将存储节点设备克隆到新的存储设备。


* 对于管理节点设备，源节点设备和目标设备不需要是相同的设备型号；但是，更改设备型号可能需要更换电缆或 SFP 模块。
+
例如，您可以将 SG1000 节点设备更换为 SG100 ，也可以将 SG100 设备更换为 SG1000 设备。

* 对于存储节点设备、源节点设备和目标设备不必是相同类型的设备；但是：
+
** 目标设备必须比源设备具有更大的存储容量。
+
例如、您可以将SG5700节点设备更换为SG6000设备。

** 目标设备的对象存储卷数量必须等于或大于源设备。
+
例如，您不能用 SGF6112 设备（12 个对象存储卷）替换 SG6000 节点设备（16 个对象存储卷）。





请联系您的 StorageGRID 销售代表，以帮助您选择兼容的替代设备来克隆 StorageGRID 安装中的特定设备节点。



[[prepare-to-clone-an-appliance-node]]
== 准备克隆设备节点

克隆设备节点之前，您必须具有以下信息：

* 从网络管理员处获取网格网络的临时 IP 地址，以便在初始安装期间与目标设备配合使用。如果源节点属于管理网络或客户端网络，请获取这些网络的临时 IP 地址。
+
临时IP地址通常与要克隆的源节点设备位于同一子网上、克隆完成后不需要。源设备和目标设备都必须连接到 StorageGRID 的主管理节点，才能建立克隆连接。

* 如果在源节点上配置为静态的目标节点的任何端口上启用 DHCP，请确保没有任何源节点 MAC 地址的永久 DHCP 租约。否则，可能会在克隆过程结束时导致 IP 地址冲突。
* 确定要使用哪个网络克隆数据传输流量，从而在不降低 StorageGRID 网络性能或数据可用性的情况下提供最佳数据传输性能。
+

NOTE: 使用 1-GbE 管理网络进行克隆数据传输会导致克隆速度变慢。

* 确定是否将在目标设备上使用密钥管理服务器 (KMS) 进行节点加密，以便您可以在克隆之前在初始目标设备安装期间启用节点加密。您可以检查源设备节点上是否启用了节点加密，如link:../installconfig/optional-enabling-node-encryption.html["正在启用节点加密"]。
+
源节点和目标设备可以具有不同的节点加密设置，但以下情况除外。不支持从未加密节点源到以下设备的节点加密目标的节点克隆：

+
** 不带节点加密的 SGF6112 节点设备到带节点加密的 SGF6112 设备
** 不带节点加密的 SG1100 节点设备到带节点加密的 SG1100 设备
** 没有节点加密的 SG1200 节点设备到具有节点加密的 SG1200 设备
** 不带节点加密的 SG110 节点设备到带节点加密的 SG110 设备
** 没有节点加密的 SG120 节点设备到具有节点加密的 SG120 设备


+
在数据传输过程中以及目标节点重新启动并加入电网时，数据解密和加密会自动执行。

* 确定是否应将目标设备上的 RAID 模式从其默认设置更改，以便您可以在克隆之前的初始目标设备安装过程中指定此信息。您可以在 Grid Manager 中的 *Nodes* 页面上查看有关源设备节点当前 RAID 模式的信息。选择设备的 *Hardware* 选项卡。
+
源节点和目标设备可以具有不同的 RAID 设置。

* 规划足够的时间以完成节点克隆过程。将数据从运行中的存储节点传输到目标设备可能需要几天时间。计划一次克隆，尽可能地减少对业务的影响。
* 一次只能克隆一个设备节点。克隆可能会阻止您同时执行其他 StorageGRID 维护功能。
* 克隆设备节点后，您可以使用已恢复预安装状态的源设备作为克隆另一个兼容节点设备的目标。

