---
permalink: commonhardware/how-appliance-node-cloning-works.html 
sidebar: sidebar 
keywords: storagegrid, appliance node cloning, appliance node clone 
summary: 您可以在 StorageGRID 中克隆设备节点，以使用设计较新或功能增强的设备。克隆会将有关现有节点的所有信息传输到新设备、提供易于执行的硬件升级过程、并为停用和扩展以更换设备提供替代方案。 
---
= 设备节点克隆：概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在 StorageGRID 中克隆设备节点，以使用设计较新或功能增强的设备。克隆会将有关现有节点的所有信息传输到新设备、提供易于执行的硬件升级过程、并为停用和扩展以更换设备提供替代方案。

通过设备节点克隆，您可以轻松地将网格中的现有设备节点（源）替换为同一逻辑 StorageGRID 站点中的兼容设备（目标）。此过程会将所有数据传输到新设备，从而使其投入使用以更换旧设备节点，并使旧设备处于预安装状态。



== 为何克隆设备节点？

如果需要，您可以克隆设备节点：

* 更换即将达到使用寿命的设备。
* 升级现有节点以利用经过改进的设备技术。
* 增加网格存储容量，而不更改 StorageGRID 系统中的存储节点数。
* 提高存储效率，例如将 RAID 模式从 DDP-8 更改为 DDP-16 或 RAID-6 。
* 高效地实施节点加密，以允许使用外部密钥管理服务器（ KMS ）。




== 使用的是哪个 StorageGRID 网络？

克隆可通过三个 StorageGRID 网络中的任何一个将数据从源节点直接传输到目标设备。通常使用网格网络，但如果源设备连接到这些网络，您也可以使用管理网络或客户端网络。选择用于克隆流量的网络，该网络可在不降低 StorageGRID 网络性能或数据可用性的情况下提供最佳数据传输性能。

安装替代设备时，必须为 StorageGRID 连接和数据传输指定临时 IP 地址。由于替代设备与其替代的设备节点属于同一网络、因此您必须为此替代设备上的每个网络指定临时IP地址。



== 目标设备兼容性

替代设备的类型必须与要替换的源节点相同，并且这两个设备都必须属于同一逻辑 StorageGRID 站点。

* 替代服务设备可以不同于要替换的管理节点或网关节点。
+
** 您可以将SG100源节点设备克隆到SG110、SG1000或SG1100服务目标设备。将SG100克隆到SG1000或SG1100服务目标设备可为管理节点或网关节点提供更大的功能。
** 您可以将SG110源节点设备克隆到SG1100服务设备目标、以便为管理节点或网关节点提供更大的功能。
** 您可以将SG1000源节点设备克隆到SG100、SG110或SG1100服务目标设备。通过将SG1000克隆到SG100或SG110服务目标设备、您可以为要求更苛刻的应用程序重新部署SG1000。
** 您可以将SG1100源节点设备克隆到SG110服务目标设备、以便为要求更高的应用程序重新部署SG1100。
+
例如、如果要将SG1100或SG1000源节点设备用作管理节点、而您希望将其用作专用负载平衡节点。

** 将SG1100源节点设备更换为SG110服务目标设备会将网络端口的最大速度从100-GbE降低到25-GbE。
** 将 SG1000 源节点设备更换为 SG100 服务目标设备会将网络端口的最大速度从 100-GbE 降低到 25-GbE 。
** 服务设备具有不同的网络连接器。更改设备类型可能需要更换缆线或 SFP 模块。


* 更换用的存储设备必须比要更换的存储节点具有更大的容量。
+
** 如果目标存储设备与源节点具有相同数量的驱动器、则目标设备中的驱动器必须具有更大容量(以TB为单位)。
** 如果您计划在目标节点上使用与源节点上相同的RAID模式、 或者存储效率较低的RAID模式(例如从RAID 6切换到DDP)、目标设备中的驱动器必须大于源设备中的驱动器(以TB为单位)。
** 如果由于安装了固态驱动器(SSD)、目标存储设备中安装的标准驱动器数量小于源节点中的驱动器数量、则目标设备中标准驱动器的总存储容量(以TB为单位) 必须超过源存储节点中所有驱动器的总功能驱动器容量。
+
例如、在将包含60个驱动器的SG5760源存储节点设备克隆到包含58个标准驱动器的SG6060目标设备时、应在克隆前在SG6060目标设备中安装更大的驱动器、以保持存储容量。(目标设备中包含SSD的两个驱动器插槽不包括在设备总存储容量中。)

+
但是、如果为一个包含60个驱动器的SG5760源节点设备配置了SANtricity 动态磁盘池DDP-8、则为一个包含58个驱动器且驱动器大小相同的SG6060目标设备配置DDP-16可能会使SG6060设备成为有效的克隆目标、因为它提高了存储效率。

+
您可以在网格管理器的 * 节点 * 页面上查看有关源设备节点当前 RAID 模式的信息。选择设备的 * 存储 * 选项卡。



* 目标存储设备中的卷数必须大于或等于源节点中的卷数。即使目标设备的容量大于源节点、您也无法将包含16个对象存储卷(rangedb)的源节点克隆到包含12个对象存储卷的目标存储设备。大多数存储设备都有16个对象存储卷、但只有12个对象存储卷的SGF6112存储设备除外。




== 哪些信息不会克隆？

以下设备配置不会在克隆期间传输到替代设备。您必须在更换设备的初始设置期间对其进行配置。

* BMC 接口
* 网络链路
* 节点加密状态
* SANtricity 系统管理器（适用于存储节点）
* RAID 模式（适用于存储节点）




== 哪些问题会阻止克隆？

如果在克隆时遇到以下任何问题，则克隆过程将暂停并生成错误消息：

* 网络配置错误
* 源设备与目标设备之间缺乏连接
* 源设备和目标设备不兼容
* 对于存储节点，是指容量不足的替代设备


要继续克隆，必须解析每个问题描述 。
